apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo
  namespace: a-team
spec:
  compositionRef:
    name: azure-postgresql
  id: silly-demo
  parameters:
    size: small
    version: "14"
